apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deploy
spec:
 replicas: 10
 selector:
   matchLabels:
     app: jobpro-dep-app
 template:
   metadata:
     name: my-deploy
     labels:
       app: jobpro-dep-app
   spec:
     containers:
     - image: 6717/ping
       name: mywebcont
       imagePullPolicy: IfNotPresent 
 
